export const citydata=[
    "Dubai",
    "Abu Dhabi",
    "Sharjah",
    "Ras Al Kima",
    "Umm Al-Quwain",
    "Ajman",
    "Jeddah",
    "Mecca",
    "Riyadh"
    
]



// Saudi Arabia cities
export const jeddahCities = [
    "AL-Fayhaa",
    "Abruq Ar-Roghama",
    "Ad-Dageeg",
    "Ad-Difaa Al-Jawi (Air Defense)",
    "Air Defense Residence",
    "Al-Adl",
    "Al-Ahmadiya",
    "Al-Ajaweed",
    "Al-Ajwad",
    "Al-Amariya",
    "Al-Amir Fawaz",
    "Al-Andalus",
    "Al-Aziziya",
    "Al-Baghdadiya Al-Gharbiya",
    "Al-Baghdadiya Ash-Sharqiya",
    "Al-Balad",
    "Al-Basateen",
    "Al-Bawadi",
    "Al-Bokhariya",
    "Al-Corniche",
    "Al-Faihaa",
    "Al-Faysaliya",
    "Al-Goaid",
    "Al-Gonfoda",
    "Al-Gozain",
    "Al-Hamdaniya59. Al-Salhiya",
    "Al-Hamraa",
    "Al-Harazat",
    "Al-Hindawiya29. As-Saheifa",
    "Al-Iskan Al-janoubi89. At-Tawfeeq",
    "Al-Jamaa",
    "Al-Jamoum",
    "Al-Jawhara",
    "Al-Kandra",
    "Al-Karanteena",
    "Al-Khalidiya",
    "Al-Khumra",
    "Al-Kuwait",
    "Al-Layth",
    "Al-Mahjar",
    "Al-Mahrogat",
    "Al-Majid",
    "Al-Manar",
    "Al-Marwa",
    "Al-Masfa",
    "Al-Matar Al-Gadeem (old airport)",
    "Al-Mohamadiya",
    "Al-Mokhwa",
    "Al-Montazahat",
    "Al-Morsalat",
    "Al-Mosadiya",
    "Al-Mosharafa",
    "Al-Mostawdaat",
    "Al-Murjan",
    "Al-Nozla Ash-Sharqiya",
    "Al-Olayia",
    "Al-Qurayat",
    "Al-Salam",
    "Al-Taghr",
    "Al-Thaalba",
    "Al-Waha",
    "Al-Wazeeriya",
    "Al-Woroud",
    "An-Naeem",
    "An-Nahda",
    "An-Naseem",
    "An-Nour",
    "An-Nozha",
    "An-Nozla Al-Yamaniya",
    "Ar-Rabie",
    "Ar-Rabwa",
    "Ar-Rawabi",
    "Ar-Rawdha",
    "Ar-Rehaily",
    "Ar-Rihab",
    "Ar-Robou",
    "Ar-Roweis",
    "As-Sabeel",
    "As-Safa",
    "As-Salamah",
    "As-Salmiya",
    "As-Samer",
    "As-Sanabil",
    "As-Showag",
    "As-Sinaiya (Bawadi)",
    "As-Sulaimaniya",
    "Ash-Sharafiya",
    "Ash-Shati",
    "Ash-Shoola",
    "At-Tarhil (deportation)",
    "Az-Zahraa",
    "Bab Makkah",
    "Bab Shareif",
    "Bahra",
    "Bani Malik",
    "Braiman",
    "East Al-Khat As-Sarei",
    "Gholail",
    "Gowieza",
    "Industrial City (Mahjar)",
    "Kholais",
    "Kilo 10",
    "Kilo 11",
    "Kilo 13119. Al-Makarona",
    "Kilo 14",
    "Kilo 2",
    "Kilo 3",
    "Kilo 5",
    "Kilo 7",
    "Kilo 8",
    "King Abdul Al-Aziz University",
    "King Faisal Guard City",
    "King Faisal Navy Base",
    "Madayin Al-Fahad",
    "Madinat As-Sultan",
    "Mokhatat Al-Aziziya",
    "Mokhatat Al-Haramain",
    "Mokhatat Al-Huda",
    "Mokhatat Ar-Riyadh",
    "Mokhatat Shamal Al-Matar",
    "Mokhtat Zahrat Ash-Shamal",
    "National Guard Residence",
    "Obhour Al-Janobiya",
    "Obhour Shamaliya",
    "Petromin",
    "Prince Abdel Majeed",
    "Rabegh",
    "Thowal",
    "Um As-Salam",
    "Um Hablain",
    "Wadi Fatma"
  ];
  
  export const meccaCities = [
    'Ajyad fortress',
    'Al Adl',
    'Al Faisaliah',
    'Al Hindawiyah',
    'Al Iskan',
    'Al Jumaizah',
    'Al Maabdah',
    'Al Muaisem',
    'Al Rasaifah',
    'Al Shoqiyah',
    'Al Shubaikah',
    'Al Sulaymaniyyah',
    'Al Utaybiyyah',
    'Al Zahir',
    'Al Zahra',
    'Al faisaliah',
    'Al-Khalidiya',
    'Aziziyah',
    'Gazza',
    'Jabal Al Nour',
    'Jabal Omar',
    'Jurhum',
    'Misfalah',
    'Muzdalifah',
    'Shar Mansur'
  ];
  
  export  const riyadhCities = [
    "Ad Difa'",
    'Al Aziziyah',
    'Al Iskan',
    'Al Izdihar',
    "Al-'Olayya",
    "Al-'Oud",
    'Al-Aqiq',
    'Al-Dirah',
    'Al-Fayha',
    'Al-Ghadir',
    'Al-Hamra',
    "Al-M'aizliyyah",
    "Al-Ma'athar",
    'Al-Malaz',
    'Al-Malga',
    'Al-Manakh',
    'Al-Manar',
    'Al-Mansoorah',
    'Al-Mansuriyya',
    'Al-Margab',
    'Al-Marwah',
    "Al-Masani'",
    'Al-Masif',
    'Al-Mugharrazat',
    "Al-Murabba'",
    'Al-Murooj',
    'Al-Nadheem',
    'Al-Nafil',
    'Al-Nahdhah',
    'Al-Naseem',
    'Al-Naseem (East)',
    'Al-Qadisiyah',
    'Al-Qayrawan',
    'Al-Qouds',
    'Al-Rabwah',
    'Al-Rawdhah',
    'Al-Rayyan',
    'Al-Rimayah',
    "Al-Sa'adah",
    'Al-Sahafa',
    'Al-Selayy',
    'Al-Shemaysi',
    'Al-Shifa',
    'Al-Sulaymaniyah',
    'Al-Urayja',
    'Al-Urayja (West)',
    'Al-Urayja Al-Wusta (Mid-Urayja)',
    'Al-Wadi',
    'Al-Wurood',
    'Al-Yamamah',
    'As-Salam',
    'As-Suwaidi',
    'As-Suwaidi (West)',
    'Deerab',
    'Dharat Laban',
    'Dharat Nemar',
    'Gharnatah',
    'Hazm',
    'Hijrat Laban',
    'Hittin',
    'Irqah',
    'Jabrah',
    'Jarir',
    "Khashm Al-'Aan",
    'King Fahd District',
    'Manfuha',
    'Manfuha Al-Jadidah',
    "Mi'kal",
    'Nemar',
    'Otayyigah',
    'Qurtubah',
    'Salam',
    'Shubra',
    'Sultanah',
    'Tuwaiq'
  ];
  
  // UAE cities
  export const dubaiCities = [
    'Abu Hail',
    'Al Amardhi',
    'Al Bada',
    'Al Baraha',
    'Al Barsha',
    'Al Buteen',
    'Al Buteen',
    'Al Dhagaya',
    'Al Etihad',
    'Al Furjan',
    'Al Garhoud',
    'Al Hamriya',
    'Al Hamriya Port',
    'Al Hudaiba',
    'Al Jaddaf',
    'Al Jafiliya',
    'Al Karama',
    'Al Kefaf',
    'Al Khabisi',
    'Al Mamzar',
    'Al Manara',
    'Al Mankhool',
    'Al Markada',
    'Al Mashreq',
    'Al Mizhar',
    'Al Muntazah',
    'Al Muraqqabat',
    'Al Murar',
    'Al Muteena',
    'Al Nahda',
    'Al Quoz',
    'Al Qusais',
    'Al Ras',
    'Al Rashidiya',
    'Al Reem',
    'Al Rifa',
    'Al Rigga',
    'Al Sabkha',
    'Al Safa',
    'Al Satwa',
    'Al Shindagha',
    'Al Souk Al Kabir',
    'Al Sufouh',
    'Al Twar',
    'Al Waheda',
    'Al Warqaa',
    'Al Wasl',
    'Ayal Nasir',
    'Bu Kadra',
    'Business Bay',
    'Damac hills',
    'Discovery Gardens',
    'Downtown Dubai',
    'Dubai International Airport',
    'Dubai International City',
    'Dubai Investments Park',
    'Dubai Marina',
    'Dubai hills',
    'Emirates Hills',
    'Hor Al Anz',
    'Industrial Area',
    'Internet City',
    'Jebel Ali Village',
    'Jumeirah Islands',
    'Jumeirah Lake Towers',
    'Mirdif',
    'Motor city',
    'Mudon',
    'Muhaisnah',
    'Nad Al Hammar',
    'Naif',
    'Nad Shamma',
    'Port Rashid',
    'Port Saeed',
    'Ras Al Khor',
    'Ras Al Khor',
    'Rigga',
    'Saheel',
    'Sport city',
    'Studio city',
    'The Gardens',
    'The Greens',
    'Trade Centre 1',
    'Trade Centre 2',
    'Umm Al Sheif',
    'Umm Hurair',
    'Umm Ramool',
    'Umm Suqeim',
    'Warisan',
    'Zabeel'
  ];
  
  export  const abuDahbiCities = [
    'Al Baladia',
    'Al Dhafrah',
    'Al bateen',
    'Al-Bahiyah',
    'Al-Shahamah',
    'Jubail Island',
    'Khalifa Port',
    'Masdar City',
    'Saadiyat Island',
    'Yas Island'
  ];
  
  export const sharjahCities = [
    'Al Layyeh',
    'Al Majaz',
    'Al Nabba',
    'Al Nahda',
    'Al Taawun',
  ];
  
  export const rasAlkimaCities = [
    'Al Darbijaniyah',
    'Al Dhait',
    'Al Hamra',
    'Al Hudaihbah',
    'Al Jazeera',
    'Al Juwais',
    'Al Kharan',
    'Al Nakheel',
    'Al Saih',
    'Al Seer',
    'Al Soor',
    'Al Uraibi',
    'Al Zahra',
    'Al Zaith',
    'Bourairat',
    'Dahan',
    'Julan',
    'Julfar',
    'Khuzam',
    'Mamourah',
    'Maareed',
    'Nakheel'
  ];
  
  export const ummAlQuwainCities = [
    'Al Aahad',
    'Al Abraq',
    'Al Atheab',
    'Al Door',
    'Al Haditha',
    'Al Hamrah',
    'Al Haweah',
    'Al Khor',
    'Al Madar',
    'Al Maidan',
    'Al Medfeq',
    'Al Raas',
    'Al Rafaah',
    'Al Ramlah',
    'Al Reqqah',
    'Al Rowdah',
    'Al Salmah',
    'Dar Al Baidah',
    'Defence Camp',
    'Emirates Modern Industrial',
    'Green Belt',
    'Industrial Area',
    'Lamagdar',
    'Latin',
    'Shanteer'
  ];
  
  export const ajmanCities = [
    'Ajman City Center',
    'Ajman Corniche',
    'Ajman Free Zone',
    'Ajman Khor',
    'Ajman Marina',
    'Ajman Pearl',
    'Ajman Port',
    'Ajman Uptown',
    'Al Ameera Village',
    'Al Bustan',
    'Al Butain',
    'Al Dhran',
    'Al Hamidiya',
    'Al Hamriya',
    'Al Helio',
    'Al Jurf',
    'Al Muntazi',
    'Al Mushairef',
    'Al Muwayhat',
    'Al Naemiyah',
    'Al Nakhil',
    'Al Naseem',
    'Al Owan',
    'Al Rashidiya',
    'Al Rifaah',
    'Al Rowdha',
    'Al RumailahAl Sawan',
    'Al Zahra',
    'Al Zora',
    'Garden City',
    'Green City',
    'Hatta',
    'Ittihad Village',
    'Marmooka City',
    'Masfout',
    'Mazeria',
    'Meadows Ajman',
    'Meidan Al Tallah',
    'Mushairef',
    'Safia Island',
    'Subaikah'
  ]
  